---
title: "Work_in_progres"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
library(data.table)
library(R.utils)
library(readr)
library(devtools)
library(tidyverse)
library(knitr)
library(plotly)
library(lubridate)
library(gapminder)
library(gganimate)
library(ggplot2)
library(sf)
library(rnaturalearth)
library(maps)
library(ggthemes)
library(hrbrthemes)
library(gifski)
library(geosphere)
```


```{r}
#https://www.r-graph-gallery.com/how-to-draw-connecting-routes-on-map-with-r-and-great-circles.html

# No margin
par(mar=c(0,0,0,0))

# World map
map('world',
    col="#f2f2f2", fill=TRUE, bg="white", lwd=0.05,
    mar=rep(0,4),border=0, ylim=c(-80,80) 
)

Buenos_aires <- c(-58,-34)
Germany <- c(2,49)
Melbourne <- c(145,-38)

# Data frame
data_map <- rbind(Buenos_aires, Germany, Melbourne) %>% 
  as.data.frame()
colnames(data_map) <- c("long","lat")

# Show the cities on the map
map('world',
    col="#f2f2f2", fill=TRUE, bg="white", lwd=0.05,
    mar=rep(0,4),border=0, ylim=c(-80,80) 
)
points(x=data_map$long, y=data_map$lat, col="slateblue", cex=3, pch=20)

# Background map
map('world',
    col="#f2f2f2", fill=TRUE, bg="white", lwd=0.05,
    mar=rep(0,4),border=0, ylim=c(-80,80) 
)


# Dot for cities
points(x=data_map$long, y=data_map$lat, col="slateblue", cex=3, pch=20)

# Compute the connection between Buenos Aires and Paris
inter <- gcIntermediate(Germany,  Buenos_aires, n=50, addStartEnd=TRUE, breakAtDateLine=F)

# Show this connection
lines(inter, col="slateblue", lwd=2)
 
# Between Paris and Melbourne
inter <- gcIntermediate(Melbourne,  Germany, n=50, addStartEnd=TRUE, breakAtDateLine=F)             
lines(inter, col="slateblue", lwd=2)
```

