---
title: "Final project - scrip"
author: "Anna Clara Deniz and Anna Weronika Matysiak"
date: "`r format(Sys.time(), '%B %d, %Y | %H:%M:%S | %Z')`"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r message=FALSE, warning=FALSE, include=FALSE}
library(data.table)
library(R.utils)
library(readr)
library(devtools)
library(tidyverse)
library(knitr)
library(plotly)
library(lubridate)
library(gapminder)
library(gganimate)
library(ggplot2)
library(sf)
library(rnaturalearth)
library(maps)
library(ggthemes)
library(hrbrthemes)
library(gifski)
library(geosphere)
library(dplyr)
library(tibble)
library(leaflet)
library(rgdal)
library(gridExtra)
library(grid)
library(geojsonio)
```

```{r message=FALSE, warning=FALSE, include=FALSE}
#gunzip("migr.tsv.gz")
#dt = fread("migr.tsv", header=T, sep="\t", stringsAsFactors=F)
#read_tsv("migr.tsv")

#http://appsso.eurostat.ec.europa.eu/nui/show.do
data<-read.csv("data/data_full.csv")
```

```{r include=FALSE}
data<- data %>% 
    mutate_at(vars(Value), ~ na_if(., "")) %>% na_if(.,":") %>%
        select(!Flag.and.Footnotes)%>%na.omit()

replaceCommas<-function(x){
  x<-as.numeric(gsub("\\,", "", x))
}

data$Value<-replaceCommas(data$Value)
data$GEO[data$GEO=="Germany (until 1990 former territory of the FRG)"]<-"Germany"
```

A. Connected scatter plot of all decision by its type

```{r echo=FALSE, warning=FALSE}

plotly_data_1<-data %>% 
 filter(GEO=="European Union - 27 countries (from 2020)" | GEO=="European Union - 28 countries (2013-2020)") %>% filter(ISCO08=="Total")%>% group_by(DECISION,TIME) %>% ungroup()

plot_1<-plotly_data_1%>% group_by(DECISION)%>%plot_ly(x=~TIME, y=~Value,
                           type="scatter",color=~DECISION, mode="lines") %>%
  layout(title = "Blue Card applications status in the EU over years 2012-2019",
         xaxis = list(title = "years"),
         yaxis = list(title = "number of applications"))%>%
  layout(autosize = T)

htmlwidgets::saveWidget(plot_1, file = "plots/plot_1.html")
plot_1
```

```{r message=FALSE, warning=FALSE}
total<-data %>% 
 filter(GEO=="European Union - 27 countries (from 2020)" | GEO=="European Union - 28 countries (2013-2020)") %>% filter(ISCO08=="Total")

sum(total$Value)
```

B.OCCUPATIONS
```{r echo=FALSE, warning=FALSE}
plotly_data<-data %>%filter(DECISION=="Granted")%>% filter(GEO=="European Union - 27 countries (from 2020)" | GEO=="European Union - 28 countries (2013-2020)")%>%filter(ISCO08!="Total" & ISCO08!="Unknown")%>%filter(TIME!="2020")%>%
  group_by(ISCO08,TIME)%>%ungroup()
  
plot_2<- plotly_data%>% group_by(ISCO08)%>%plot_ly(x=~TIME, y=~Value,
                           type="scatter",color=~ISCO08, mode="lines")%>%
  layout(title = "Decision granted by type of occupation 2012-2019",
         xaxis = list(title = ""),
         yaxis = list(title = ""))%>%
  layout(autosize = T)

htmlwidgets::saveWidget(plot_2, file = "plots/plot_2.html")
plot_2
```

C. ANIMATION

```{r warning=FALSE}
ranked_by_year<-data %>%filter(DECISION=="Granted" & ISCO08=="Total")%>%filter(GEO!="European Union - 27 countries (from 2020)" & GEO!="European Union - 28 countries (2013-2020)")%>% filter(TIME!=2020)%>%
  select(TIME, GEO, Value) %>%group_by(GEO)%>% mutate(pop=cumsum(Value))%>%group_by(TIME)%>%
  arrange(TIME,-pop) %>%  
  mutate(rank = 1:n(),  pop_lbl = paste0(" ", pop))%>% filter(rank <= 15)

static_plot <- ggplot(ranked_by_year, aes(rank, group = GEO, fill=GEO, color=GEO)) +  
  geom_tile(aes(y = pop/2,
                height = pop,
                width = 0.75), alpha = 0.8) +
  geom_text(aes(y = 0, label = paste(GEO, " ")), vjust = 0.2, hjust = 1, size=4.5) +
  geom_text(aes(y=max(pop),label = paste(pop_lbl, " ")),vjust = 0.2, hjust = 0, size=4.5, col = "gray") +

 coord_flip(clip = "off", expand = FALSE) +
  scale_x_reverse() +
  scale_y_continuous(labels = scales::comma) +
   guides(color = FALSE, fill = FALSE) +
  scale_fill_discrete(guide = guide_legend(title.theme = element_text(
      size = 20), label.theme = element_text(size = 15))) +
  theme(axis.line=element_blank(),
        axis.text.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks=element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank(),
        panel.background=element_blank(),
        panel.border=element_blank(),
        panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        panel.grid.major.x = element_line( size=.1, color="grey" ),
        panel.grid.minor.x = element_line( size=.1, color="grey" ),
        plot.title=element_text(size=20, hjust=0, colour="black", vjust=-1),
        plot.caption =element_text(size=8, hjust=1, face="italic", color="grey"),
        plot.background=element_blank(),
       plot.margin = margin(2,2, 2, 4, "cm"))


animated <- static_plot+ transition_states(TIME,
transition_length = 4, state_length = 1, wrap = FALSE) +
  view_follow(fixed_x = TRUE)  +
  ease_aes('linear')+
    enter_fade()+
    exit_fade() +
  labs(title = 'Accepted aplications untill {closest_state}',  
       subtitle  =  "Cumulative increase by country from 2012")


animate(animated, 150, fps = 5,  end_pause = 50, duration = 40,
        renderer = gifski_renderer("plots/gganim.gif"))
```
D France
```{r message=FALSE, warning=FALSE}
table_1<-data%>% group_by(GEO, ISCO08)%>% mutate(pop=cumsum(Value))%>%filter(GEO=="France")%>%filter(TIME==2019)%>%
  filter(DECISION=="Granted")%>%unique()%>%
  select(GEO, ISCO08, pop)%>%
  filter(ISCO08!="Total" & ISCO08!="Unknown")%>% filter(pop!=0)%>%arrange(-pop)
table_1
```

Import Data

```{r message=FALSE, warning=FALSE}

# EU Blue Card Data
eu_data <- read_csv("data/data_partial.csv")


```

Tidy Data

```{r warning=FALSE}

# Total Accumulated Per Citizenship
citizen_data <- eu_data %>%
  mutate(Value = as.numeric(Value)) %>%
  filter (GEO %in% c("European Union - 27 countries (from 2020)", 
                     "European Union - 28 countries (2013-2020)")) %>%
  group_by(CITIZEN) %>%
  summarize(Total = sum(Value, na.rm = TRUE)) %>%
  filter(Total != 0) %>%
  arrange(desc(Total))

# Total Accumulated Per Country
geo_data <- eu_data %>%
  mutate(Value = as.numeric(Value)) %>%
  filter (!GEO %in% c("European Union - 27 countries (from 2020)", 
                      "European Union - 28 countries (2013-2020)")) %>%
  group_by(GEO) %>%
  summarize(Total = sum(Value, na.rm = TRUE)) %>%
  filter(Total != 0) %>%
  arrange(desc(Total))

# Top Countries Per Citizenship
top_geo_data <- eu_data %>%
  mutate(Value = as.numeric(Value)) %>%
  filter (!GEO %in% c("European Union - 27 countries (from 2020)", 
                      "European Union - 28 countries (2013-2020)"),
            GEO %in% head(geo_data$GEO, 10)) %>%
  group_by(GEO, CITIZEN) %>%
  summarize(Total = sum(Value, na.rm = TRUE)) %>%
  filter(Total != 0) %>%
  arrange(GEO, desc(Total))

```

Plot Data

```{r warning=FALSE}
# World Map
data("world.cities")
citizen_coordinates <- world.cities %>%
  filter (country.etc %in% head(citizen_data$CITIZEN, 10),
          capital == TRUE)

Europe <- c(2,49)
Syria <- c(36.32,33.50)        
Serbia <- c(20.50,44.83)        
Pakistan <- c(73.06,33.72)      
Mexico <- c(-99.14,19.43)         
Tunisia <- c(10.22,36.84)        
Brazil <- c(-47.91,-15.78)         
Egypt <- c(31.25,30.06)          
Iran <- c(51.43,35.67)           
USA <- c(-77.02,38.91)  
SKorea <- c(126.99,37.56)    

dots_map <- rbind(Europe, Syria, Serbia, Pakistan, Mexico, 
                  Tunisia, Brazil, Egypt, Iran, USA, SKorea) %>% 
  as.data.frame()
colnames(dots_map) <- c("long","lat")

par(mar=c(0,0,0,0))
map('world',
    col="#f2f2f2", fill=TRUE, bg="white", lwd=0.05,
    mar=rep(0,4),border=0, ylim=c(-80,80))

points(x=dots_map$long, y=dots_map$lat, col="slateblue", cex=2, pch=20) 

inter <- gcIntermediate(Syria, Europe, n=50, addStartEnd=TRUE, breakAtDateLine=F) 
lines(inter, col="skyblue", lwd=1)  

inter <- gcIntermediate(Serbia, Europe, n=50, addStartEnd=TRUE, breakAtDateLine=F) 
lines(inter, col="skyblue", lwd=1) 

inter <- gcIntermediate(Pakistan, Europe, n=50, addStartEnd=TRUE, breakAtDateLine=F) 
lines(inter, col="skyblue", lwd=1) 

inter <- gcIntermediate(Mexico, Europe, n=50, addStartEnd=TRUE, breakAtDateLine=F) 
lines(inter, col="skyblue", lwd=1) 

inter <- gcIntermediate(Tunisia, Europe, n=50, addStartEnd=TRUE, breakAtDateLine=F) 
lines(inter, col="skyblue", lwd=1) 

inter <- gcIntermediate(Brazil, Europe, n=50, addStartEnd=TRUE, breakAtDateLine=F) 
lines(inter, col="skyblue", lwd=1) 

inter <- gcIntermediate(Egypt, Europe, n=50, addStartEnd=TRUE, breakAtDateLine=F) 
lines(inter, col="skyblue", lwd=1) 

inter <- gcIntermediate(Iran, Europe, n=50, addStartEnd=TRUE, breakAtDateLine=F) 
lines(inter, col="skyblue", lwd=2) 

inter <- gcIntermediate(USA, Europe, n=50, addStartEnd=TRUE, breakAtDateLine=F)
lines(inter, col="skyblue", lwd=1) 

inter <- gcIntermediate(SKorea, Europe, n=50, addStartEnd=TRUE, breakAtDateLine=F) 
lines(inter, col="skyblue", lwd=1)
```

```{r warning=FALSE}

# Europe Interactive Map
geo_data <- mutate(geo_data, "CountryCode" = c("DE", "FR", "PL", "LU", "IT", "CZ", "AT", "LV", "LT", "BG", "RO", "NL", "HR", "FI", "BE", "ES", "SK", "EE", "MT", "SK", "HU", "PT", "SE", "EL"))

m <- leaflet() %>% 
  addTiles() %>% 
  setView( lng = 15, lat = 49, zoom = 3)

```

```{r warning=FALSE}

# Bar Plots
p_europe <- citizen_data %>% 
  filter(CITIZEN %in% head(citizen_data$CITIZEN,5)) %>% 
  ggplot(aes(x = reorder(CITIZEN, Total), y = Total)) +
  geom_bar(stat = "identity", fill = "skyblue", width=0.5) +
  theme(plot.title = element_text(hjust = 0.5, face = "bold"),
        axis.text.y = element_text(face = "bold"),
        axis.text.x = element_text(face = "bold"),
        panel.background = element_rect(fill = NA)) +
  coord_flip() +
  labs(title = "European Union", x = "", y = "")

p_germany <- top_geo_data %>% 
  filter(GEO == "Germany (until 1990 former territory of the FRG)")  
p_germany <- p_germany %>% 
  filter(CITIZEN %in% head(p_germany$CITIZEN,5)) %>% 
  ggplot(aes(x = reorder(CITIZEN, Total), y = Total)) +
  geom_bar(stat = "identity", fill = "slateblue", width=0.5) +
  theme(plot.title = element_text(hjust = 0.5, face = "bold"),
        axis.text.y = element_text(face = "bold"),
        axis.text.x = element_text(face = "bold"),
        panel.background = element_rect(fill = NA)) +
  coord_flip() +
  labs(title = "Germany", x = "", y = "")

p_france <- top_geo_data %>% 
  filter(GEO == "France") 
p_france <- p_france %>% 
  filter(CITIZEN %in% head(p_france$CITIZEN,5)) %>% 
  ggplot(aes(x = reorder(CITIZEN, Total), y = Total)) +
  geom_bar(stat = "identity", fill = "slateblue", width=0.5) +
  theme(plot.title = element_text(hjust = 0.5, face = "bold"),
        axis.text.y = element_text(face = "bold"),
        axis.text.x = element_text(face = "bold"),
        panel.background = element_rect(fill = NA)) +
  coord_flip() +
  labs(title = "France", x = "", y = "")
p_france

p_poland <- top_geo_data %>% 
  filter(GEO == "Poland")
p_poland <- p_poland %>% 
  filter(CITIZEN %in% head(p_poland$CITIZEN,5)) %>% 
  ggplot(aes(x = reorder(CITIZEN, Total), y = Total)) +
  geom_bar(stat = "identity", fill = "slateblue", width=0.5) +
  theme(plot.title = element_text(hjust = 0.5, face = "bold"),
        axis.text.y = element_text(face = "bold"),
        axis.text.x = element_text(face = "bold"),
        panel.background = element_rect(fill = NA)) +
  coord_flip() +
  labs(title = "Poland", x = "", y = "")

p_luxembourg <- top_geo_data %>% 
  filter(GEO == "Luxembourg")
p_luxembourg <- p_luxembourg %>%
  filter(CITIZEN %in% head(p_luxembourg$CITIZEN,5)) %>% 
  ggplot(aes(x = reorder(CITIZEN, Total), y = Total)) +
  geom_bar(stat = "identity", fill = "slateblue", width=0.5) +
  theme(plot.title = element_text(hjust = 0.5, face = "bold"),
        axis.text.y = element_text(face = "bold"),
        axis.text.x = element_text(face = "bold"),
        panel.background = element_rect(fill = NA)) +
  coord_flip() +
  labs(title = "Luxembourg", x = "", y = "")

p_italy <- top_geo_data %>% 
  filter(GEO == "Italy") 
p_italy <- p_italy %>% 
  filter(CITIZEN %in% head(p_italy$CITIZEN,5)) %>% 
  ggplot(aes(x = reorder(CITIZEN, Total), y = Total)) +
  geom_bar(stat = "identity", fill = "slateblue", width=0.5) +
  theme(plot.title = element_text(hjust = 0.5, face = "bold"),
        axis.text.y = element_text(face = "bold"),
        axis.text.x = element_text(face = "bold"),
        panel.background = element_rect(fill = NA)) +
  coord_flip() +
  labs(title = "Italy", x = "", y = "")

p_czechia <- top_geo_data %>% 
  filter(GEO == "Czechia") 
p_czechia <- p_czechia %>%
  filter(CITIZEN %in% head(p_czechia$CITIZEN,5)) %>% 
  ggplot(aes(x = reorder(CITIZEN, Total), y = Total)) +
  geom_bar(stat = "identity", fill = "slateblue", width=0.5) +
  theme(plot.title = element_text(hjust = 0.5, face = "bold"),
        axis.text.y = element_text(face = "bold"),
        axis.text.x = element_text(face = "bold"),
        panel.background = element_rect(fill = NA)) +
  coord_flip() +
  labs(title = "Czechia", x = "", y = "")

p_austria <- top_geo_data %>% 
  filter(GEO == "Austria") 
p_austria <- p_austria %>% 
  filter(CITIZEN %in% head(p_austria$CITIZEN,5)) %>% 
  ggplot(aes(x = reorder(CITIZEN, Total), y = Total)) +
  geom_bar(stat = "identity", fill = "slateblue", width=0.5) +
  theme(plot.title = element_text(hjust = 0.5, face = "bold"),
        axis.text.y = element_text(face = "bold"),
        axis.text.x = element_text(face = "bold"),
        panel.background = element_rect(fill = NA)) +
  coord_flip() +
  labs(title = "Austria", x = "", y = "")

p_latvia <- top_geo_data %>% 
  filter(GEO == "Latvia") 
p_latvia <- p_latvia %>% 
  filter(CITIZEN %in% head(p_latvia$CITIZEN,5)) %>% 
  ggplot(aes(x = reorder(CITIZEN, Total), y = Total)) +
  geom_bar(stat = "identity", fill = "slateblue", width=0.5) +
  theme(plot.title = element_text(hjust = 0.5, face = "bold"),
        axis.text.y = element_text(face = "bold"),
        axis.text.x = element_text(face = "bold"),
        panel.background = element_rect(fill = NA)) +
  coord_flip() +
  labs(title = "Latvia", x = "", y = "")

p_lithuania <- top_geo_data %>% 
  filter(GEO == "Lithuania") 
p_lithuania <- p_lithuania %>% 
  filter(CITIZEN %in% head(p_lithuania$CITIZEN,5)) %>% 
  ggplot(aes(x = reorder(CITIZEN, Total), y = Total)) +
  geom_bar(stat = "identity", fill = "slateblue", width=0.5) +
  theme(plot.title = element_text(hjust = 0.5, face = "bold"),
        axis.text.y = element_text(face = "bold"),
        axis.text.x = element_text(face = "bold"),
        panel.background = element_rect(fill = NA)) +
  coord_flip() +
  labs(title = "Lithuania", x = "", y = "")

p_bulgaria <- top_geo_data %>% 
  filter(GEO == "Bulgaria")
p_bulgaria <- p_bulgaria %>% 
  filter(CITIZEN %in% head(p_bulgaria$CITIZEN,5)) %>% 
  ggplot(aes(x = reorder(CITIZEN, Total), y = Total)) +
  geom_bar(stat = "identity", fill = "slateblue", width=0.5) +
  theme(plot.title = element_text(hjust = 0.5, face = "bold"),
        axis.text.y = element_text(face = "bold"),
        axis.text.x = element_text(face = "bold"),
        panel.background = element_rect(fill = NA)) +
  coord_flip() +
  labs(title = "Bulgaria", x = "", y = "")

plot_4 <- grid.arrange(
  p_europe,
  p_germany,
  p_france,
  p_poland,
  p_luxembourg,
  p_italy,
  p_czechia,
  p_austria,
  p_latvia,
  p_lithuania,
  p_bulgaria,
  layout_matrix = rbind(c(1, 1, 2), c(3, 4, 5), c(6, 7, 8), c(9, 10, 11)),
  top = "Accumulated sum of migrants to EU countries per country of origin between 2015 and 2019")

ggsave("plots/plot_4.png", width = 18, height = 15, dpi = 400, limitsize = FALSE, plot_4)

```
